"""Batch convenience runner: anonymize one file or every file in a folder.

Accepts two input kinds:
  *.json  canonical messages: {"file_id","text","findings":[...],"job":{...}}
          (findings come from the real detection pipeline — preferred)
  *.txt   plain text: findings are generated by the BUILT-IN Tier-1 regex
          detector (emails, phones, cards, SSN/Aadhaar/PAN). It does NOT
          find names/orgs/locations — use real detection output for those.
"""
from __future__ import annotations

import json
import time
from pathlib import Path

from .core.detection import RegexDetector
from .runtime import Runtime, load_app_config
from .worker import Worker


def _collect(in_path: str) -> list[Path]:
    src = Path(in_path)
    if src.is_dir():
        return sorted(p for p in src.iterdir() if p.suffix.lower() in (".json", ".txt"))
    if src.suffix.lower() not in (".json", ".txt"):
        raise SystemExit(f"unsupported input type: {src.suffix} (use .json or .txt)")
    return [src]


def run_batch(
    in_path: str,
    target: str = "training",
    config: str = "config/app.yaml",
    job_id: str | None = None,
    tenant: str = "default",
) -> int:
    files = _collect(in_path)
    if not files:
        print(f"no .json/.txt files found in {in_path}")
        return 1

    cfg = load_app_config(config) if Path(config).exists() else {}
    rt = Runtime(cfg)
    worker = Worker(rt)
    detector = RegexDetector()
    job_id = job_id or f"{target}-{time.strftime('%Y%m%d-%H%M%S')}"

    txt_warned = False
    statuses: dict[str, str] = {}
    for f in files:
        if f.suffix.lower() == ".json":
            msg = json.loads(f.read_text(encoding="utf-8"))
            msg.setdefault("file_id", f.stem)
            job = msg.setdefault("job", {})
            job.setdefault("job_id", job_id)
            job.setdefault("downstream_target", target)
            job.setdefault("tenant_id", tenant)
        else:
            if not txt_warned:
                print("note: .txt inputs use the built-in structured-PII detector only "
                      "(no names/orgs). Feed detection-pipeline JSON for full coverage.")
                txt_warned = True
            text = f.read_text(encoding="utf-8")
            msg = {
                "file_id": f.stem,
                "text": text,
                "findings": [
                    {"entity_type": d.entity_type, "start": d.start, "end": d.end,
                     "confidence": d.confidence, "tier": d.tier}
                    for d in detector.detect(text)
                ],
                "job": {"job_id": job_id, "downstream_target": target, "tenant_id": tenant},
            }
        status = worker.process(msg)
        statuses[f.name] = status
        print(f"  {f.name}: {status}")

    delivered = sum(1 for s in statuses.values() if s == "VERIFIED")
    quarantined = sum(1 for s in statuses.values() if s == "LEAK_DETECTED")
    print(f"\n{delivered} delivered, {quarantined} quarantined")
    print(f"masked output: {rt.output_dir / job_id}/")
    if quarantined:
        print(f"quarantined receipts: {rt.output_dir / 'quarantine' / job_id}/")
    return 3 if quarantined else 0
